### ISSUE TITLE
Add octo version command

### ISSUE THREAD

**Issue by darron** [octohost/octohost#100]
To output at least:

1. Docker version.
2. SHA version of code this was built off of for both `octohost/octohost` and `octohost/octohost-cookbook`

Anything else?

**Comment by joshuacox** [comment]
version would be good, double bonus points for SHA summing everything in the project (Berksfile.lock etc)

**Comment by darron** [comment]
Maybe I'll even check out a copy of the code - so you can look right through it.

**Comment by darron** [comment]
See this command for how some of that information is gathered:

https://github.com/octohost/octohost-cookbook/commit/6c1f51d92e399446761a042b56db5676d12e9fb9

**Comment by darron** [comment]
Example output:

```
root@default-ubuntu-1404:/etc/default# octo version
==== octohost version ====
octohost: https://github.com/octohost/octohost/commit/166ffbb1545d6dc5a0189a1e65eecbe4c078fb61
cookbook: https://github.com/octohost/octohost-cookbook/commit/b8ff72198e83df3e316ca5cc84995a11c3bc3378
==== Docker Version ====
Client version: 1.5.0
Client API version: 1.17
Go version (client): go1.4.1
Git commit (client): a8a31ef
OS/Arch (client): linux/amd64
Server version: 1.5.0
Server API version: 1.17
Go version (server): go1.4.1
Git commit (server): a8a31ef
==== Consul Version ====
Consul v0.4.1
Consul Protocol: 2 (Understands back to: 1)
All source code for this installation is in /var/archive/
```

**Comment by joshuacox** [comment]
nice just pulled it down, looks great
