### ISSUE TITLE
Automatically restarting services when octohost reboots.

### ISSUE THREAD

**Issue by NigelThorne** [octohost/octohost#109]
I need the services to automatically restart when the octohost server reboots. 

I tried adding "--restart=always" to the launch command in octo. This works to some extend. The issue is that the port used changes, and the nginx config doesn't.

I would like a way for this to automatically update. 

I was thinking I could somehow automatically run "octo services:clear && octo services:register".

This doesn't work however because "docker ps" lists the restarted container's image by it's sha, not it's name. I can work around that, but I would also have to have something trigger this command in the first place. It would have to run after docker has restarted the containers.

A design that sidesteps this problem is: 

If octohost registered images with docker, and told them to start, and relied on a separate service watching docker to notice the starting container and trigger a change in consult config. This in turn would update the nginx config as it does now. 

This way ... if the server restarts, the containers restart, and their "starting" event triggers the consult config to be updated again, and nginx is updated. 

Other alternatives require polling to detect the discrepancy between the port known by consult and the one exposed by docker. 

Thoughts?

**Comment by darron** [comment]
I have been thinking about this - I think a variation on this is likely to be the best way to make this happen:

https://docs.docker.com/articles/host_integration/

For example:

```
description "{container-name} container"
author "Me"
start on filesystem and started docker
stop on runlevel [!2345]
respawn
script
  /usr/bin/octo {container-name} start
end script
```

What do you think?

**Comment by NigelThorne** [comment]
If docker is setup to restart (using upstart say), then docker will
automatically restart the images that were started with the restart flag
set.
We could launch images with the reset flag set if there is an octo comment
in the docker file.

That's what I'm currently doing.

**Comment by NigelThorne** [comment]
Ignore me.. I forgot about the port number changes.

**Comment by darron** [comment]
Between these two commits:

https://github.com/octohost/octohost-cookbook/commit/f175987

https://github.com/octohost/octohost/commit/536ebd3

This may solve your problem.

Testing it myself.

**Comment by darron** [comment]
This is complete now with the latest release.
