### ISSUE TITLE
Add an `apt-get -y upgrade` to the first shell provisioner.

### ISSUE THREAD

**Issue by darron** [octohost/octohost#122]
That way, it's always up to date with all of the current packages when it's built at least.

**Comment by joshuacox** [comment]
you know I think including the apt cookbook ensures that already happens (*which octohost-cookbook already does)

https://github.com/opscode-cookbooks/apt

**Comment by darron** [comment]
It does an `update` - but not an `upgrade`.

I was working on a new box I just deployed yesterday for testing and found that it had over 75 old packages. 

Provider's base images seem to be all over the map - some of them are relatively recently updated - this would put them all up to date when it's built.

**Comment by darron** [comment]
Closed by https://github.com/octohost/octohost-cookbook/commit/0767a811b1fea1528498d6dbef52f17857f5d7b9
