### ISSUE TITLE
specifying ports breaks http proxy

### ISSUE THREAD

**Issue by joshuacox** [octohost/octohost#123]
for example with icinga2 I've been exposing port 5665, now consul wants to make 5665 the new http port.  I've tried making the port both higher and lower than 5665, and I've even gotten rid of port 5665 altogether in the dockerfile, and yet consul still wants to stick it in the resulting conf file in `/etc/nginx/containers`.  dumping the config values with `octo config:export` does not reveal anything pointing to port 5665, so I'm kind of scratching my head as to where consul is even storing that value?  And is there a way I can force consul to choose one port for the port 80 proxy?

**Comment by darron** [comment]
Can you show me an example Dockerfile?

**Comment by joshuacox** [comment]
You should be able to throw this into an octohost to see what I mean, though icinga will prolly bork out without its DB and supporting file structure.
```
FROM    joshuacox/docker-icinga2:wheezy
MAINTAINER Josh Cox <josh 'at' webhosting coop>

# Add supervisord configuration
COPY supervisord.conf /etc/supervisor/conf.d/supervisord.conf

ADD entrypoint.sh /entrypoint.sh
RUN chmod u+x /entrypoint.sh

VOLUME  ["/var/lib/icinga2"]
VOLUME  ["/etc/icinga2"]
VOLUME  ["/etc/icinga2-classicui"]
VOLUME  ["/etc/icinga"]
VOLUME  ["/etc/icinga-web"]
VOLUME  ["/etc/dbconfig-common"]

EXPOSE 80
EXPOSE 5665

# MOUNT_FROM_HOST /exports/whc-icinga2/var/lib/icinga2 /var/lib/icinga2
# MOUNT_FROM_HOST /exports/whc-icinga2/etc/icinga2 /etc/icinga2
# MOUNT_FROM_HOST /exports/whc-icinga2/etc/icinga2-classicui /etc/icinga2-classicui
# MOUNT_FROM_HOST /exports/whc-icinga2/etc/icinga /etc/icinga
# MOUNT_FROM_HOST /exports/whc-icinga2/etc/icinga-web /etc/icinga-web
# MOUNT_FROM_HOST /exports/whc-icinga2/etc/dbconfig-common /etc/dbconfig-common
# PORTS_FROM_HOST 45664 80
# PORTS_FROM_HOST 45664 80/udp
# PORTS_FROM_HOST 5665 5665
# PORTS_FROM_HOST 5665 5665/udp
# Initialize and run Supervisor
ENTRYPOINT ["/entrypoint.sh"]
CMD ["/usr/bin/supervisord"]
```
the resulting container conf:
```
# cat /etc/nginx/containers/whc-icinga2.conf 
upstream whc-icinga2 {
  server 65.67.51.188:45664 fail_timeout=0;
  server 65.67.51.188:5665 fail_timeout=0;
  
}
server {
  listen 80;
  listen 443 ssl spdy;
  include /etc/nginx/ssl.conf;
  server_name octohost.webhosting.coop whc-icinga2.65.67.51.188.xip.io;
  location / {
    include /etc/nginx/location.conf;
    proxy_pass http://whc-icinga2;
  }
}
```
```
root@octo:/exports/whc-icinga2/etc/icinga2/conf.d# docker ps -l
CONTAINER ID        IMAGE                         COMMAND                CREATED             STATUS              PORTS                                                                                          NAMES
cb82cc742a3d        octoprod/whc-icinga2:latest   "/entrypoint.sh /usr   29 minutes ago      Up 29 minutes       0.0.0.0:5665->5665/tcp, 0.0.0.0:5665->5665/udp, 0.0.0.0:45664->80/tcp, 0.0.0.0:45664->80/udp   stoic_carson  
```

**Comment by joshuacox** [comment]
here's a repo:
https://github.com/WebHostingCoopTeam/whc-icinga2

**Comment by darron** [comment]
Yeah - I think the problem is the multiple EXPOSE commands. octohost really doesn't know what to do with that and is doing the wrong thing. Sorry about that.

**Comment by joshuacox** [comment]
No worries, I can just use a non-standard port for icinga, it's not a customer facing interface anyhow.  A workaround I was thinking about implementing anyway was a linked varnish container that had the cname assigned to it.   Have you seen any good implementations of varnish inside octohost? I see @lorello created one last august, but no files committed.
