### ISSUE TITLE
HVM Support for the Amazon AMI

### ISSUE THREAD

**Issue by girvo** [octohost/octohost#126]
Hey there, 

Currently the AMI built by `rake build_ami` gives an AMI that does not support HVM virtualisation, which means we cannot use the AMI with the (not so) new t2 instance types.

Is this a difficult change?

Cheers,
Josh

**Comment by darron** [comment]
Just patched the build template:

https://github.com/octohost/octohost-cookbook/commit/ab986281dd8dd6404e3916ae3db515dcc99e0b4a

You can use any AMI you want to build with - just use Trusty:

http://cloud-images.ubuntu.com/locator/ec2/

That help?

**Comment by darron** [comment]
This is done - the newest release is based on an HVM AMI.
