### ISSUE TITLE
Git push on a new Amazon instance does not work

### ISSUE THREAD

**Issue by girvo** [octohost/octohost#127]
Sorry about the crazy amount of tickets!

I have set up a new Octohost instance using the AMI built from master, running in a VPC on an `m1.small`. It has my SSH key in the ubuntu user, and in the git user's `authorized_keys` file. I can SSH into the box with no issues, but attempting to push the repository gives this error:

```
➜  harp git:(master) git remote add octohost git@studionone.io:harp.git
➜  harp git:(master) git push octohost master
fatal: 'harp.git' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

Any ideas?

**Comment by darron** [comment]
That usually means that your key isn't in the right format in the `/home/git/.ssh/authorized_keys` file.

This is the command you need to run:

`cat ~/.ssh/id_rsa.pub | ssh ubuntu@studionone.io "sudo gitreceive upload-key girvo"`

If your public key is a different name - substitute that - but that should fix it.

For reference, your keys should look like this:

https://github.com/nonfiction/keys/blob/master/gitreceive-keys

**Comment by darron** [comment]
You may also be running into a bug I just fixed #128 - If so - just change the `/etc/default/octohost` file:

https://github.com/octohost/octohost/commit/2002abbd6457fffac551f28173f1729dfd95b0e3

**Comment by darron** [comment]
Also - don't worry about filing bugs. If there's a problem I want to know and I want to fix it. So - hopefully you don't get too many problems - but it's a complex build and I'll fix it if I can duplicate it!

**Comment by girvo** [comment]
Tried both of those and have the same problem. Should I rebuild the AMI and set it up once more?

**Comment by darron** [comment]
I just tried a build - works fine from what I can see:

https://gist.github.com/darron/eba31d2e32265b95d977

The site is available here: http://caddy.52.12.211.211.xip.io/

If I remove the keys completely:

```
DarronFroeseDD@: git push octo master
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

If I put them in the standard ssh format it errors like this:

```
DarronFroeseDD@: git push octo master
Counting objects: 3, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (2/2), done.
Writing objects: 100% (3/3), 261 bytes | 0 bytes/s, done.
Total 3 (delta 1), reused 0 (delta 0)
remote: Base: .git
remote: Something is wrong. Your Repository name is blank!
remote:       ERROR: failed on rev 4bce6a5511dd75ae65e2c79b06af7e05ad0fc733 - push denied
To git@52.12.211.211:caddy.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'git@52.12.211.211:caddy.git'
```

I have added all your public keys that are available here: https://github.com/girvo.keys - to my server - try it yourself:

`git remote add octohost git@52.12.211.211:girvo.git`

If that doesn't work - then there's something else going on.

If you can add my key to the ubuntu user I'd be glad to help out and take a look:

https://github.com/darron.keys

But without additional logs I have no idea what's going on.

**Comment by darron** [comment]
Haven't heard back - closing for now - please re-open if you've got additional logs.
