### ISSUE TITLE
IT changed the IPaddress of my Octohost box. It broke everything. How do I fix it?

### ISSUE THREAD

**Issue by NigelThorne** [octohost/octohost#129]
I have my octohost box hosted by IT (as a VMWare box). They accidentally gave the box a non-static IP. It's now fixed, but changed.  Consul and some Octohost config files seem to hardcode in the IPaddres, so  my services aren't working since the change. 

Is there a simple way to reconfigure Octohost and Consul (and anything else that needs it.. Nginx?  etc) so the server knows it's new IPaddress?

**Comment by darron** [comment]
you should only have to change `PUBLIC_IP` and `PRIVATE_IP` in `/etc/default/octohost` - and then you may have to reload the containers:

`octo reload {container}`

That should be all you need to do.

**Comment by NigelThorne** [comment]
When I do that, then run 
octo services:catalog 
I get 
vagrant@octohost:~$ octo services:catalog
{"Node":"octodev-master","Address":"10.10.254.12","ServiceID":"blobby-49165","ServiceName":"blobby","ServiceTags":["http"],"ServicePort":49165}
{"Node":"octodev-master","Address":"10.10.254.12","ServiceID":"consul","ServiceName":"consul","ServiceTags":null,"ServicePort":8300}
{"Node":"octodev-master","Address":"10.10.254.12","ServiceID":"docgraph-49166","ServiceName":"docgraph","ServiceTags":["http"],"ServicePort":49166}
{"Node":"octodev-master","Address":"10.10.254.12","ServiceID":"jira_tasks-49167","ServiceName":"jira_tasks","ServiceTags":["http"],"ServicePort":49167}
{"Node":"octodev-master","Address":"10.10.254.12","ServiceID":"project_dash-49168","ServiceName":"project_dash","ServiceTags":["http"],"ServicePort":49168}

10.10.254.12 is the old IP address.

Note: I am a couple of months behind on the octohost version I am using.

**Comment by darron** [comment]
Stopping and starting all of them should reset the IP address if you've set it properly in `/etc/default/octohost`

If it's not doing that, stop them all and run:

`octo services:clear`

Another thing to check would be the Consul config file. That may have the old IP address in it as well.

**Comment by NigelThorne** [comment]
Doing ```octo stop xxx``` on all services leaves me with an empty
/etc/nginx/containsers.conf  (as expected)

```
vagrant@octohost:~$ octo services:clear
vagrant@octohost:~$ octo services:catalog
{"Node":"octodev-master","Address":"10.10.254.12","ServiceID":"consul","ServiceName":"consul","ServiceTags":null,"ServicePort":8300}
```
The only record left is "consul" itself.

Where in a vagrant build of ocotohost is the consul file?

I assume that once I change it I can do ```consul reload``` to reload it (
https://www.consul.io/docs/commands/reload.html).

**Comment by NigelThorne** [comment]
vagrant@octohost:~$ cat  /var/cache/consul/raft/peers.json
["10.10.254.12:8300"]

Consul's cache still contains the old ipaddress.

**Comment by NigelThorne** [comment]
I edited the peers.json and rebooted the machine. 

Everything is now working.
