### ISSUE TITLE
Postgres Support

### ISSUE THREAD

**Issue by derek-adair** [octohost/octohost#82]
Just thought i'd nudge this issue.  This is actually a show stopper for me.  I'm honestly just not sure how to properly deploy a django/postgres app via octohost.

For now i am having to simply install fig on my octohost machine and run fig up manually.

**Comment by joshuacox** [comment]
I still think that an external SQL server is the way to go for production, but if all you need is something up and running you can test on, then here is a working example of of a postgresql image you can put in an octohost:
https://github.com/joshuacox/postgresocto

it is based on sameersbn's:
https://github.com/sameersbn/docker-postgresql

I also know you were working on Odoo?  Here's a working example of that (postgres selfcontained in the same docker container):
https://github.com/joshuacox/octodoo

adapted from version 8 of tinyerp's:
https://github.com/tinyerp/odoo-docker
