### ISSUE TITLE
slow building host gets ignored by consul

### ISSUE THREAD

**Issue by joshuacox** [octohost/octohost#99]
Not really sure where the breakdown is at this point, but here's how it usually goes, I upload a slow building docker image like this one:

https://github.com/joshuacox/docker-redmine

the nginx config gets with one of these at the top:

```
upstream example_site {
  server 127.0.0.1:404;
}
```

I wait a few minutes, and `octo restart example_site`, and then consul recognizes the first instance and assigns it's port instead of the 404 above, I then kill off the container that was just made using the `octo restart` command as the old one is now connected to nginx.  So in the end I do have a working container, but this is a bit silly.  And I'm not  sure what to go fix.  Is this even consul's fault?

**Comment by darron** [comment]
the 404 is only added if the health check is failing - and that's only added at the end of the process - so it shouldn't happen before the container is launched.

Thanks for the link to the failing box - I will try it and get back to you.

**Comment by joshuacox** [comment]
here's another example:

https://github.com/joshuacox/docker-drupal-nginx

I think it's the long build process that happens to both of them, eventually even `octo status` shows them as ok, and I can go directly to that container port on the IP and see the container is running successfully, but the nginx config never gets updated, until I do the `octo restart` that is, but then it doesn't kill the original container, so I'm confused as to where the failure is even occurring.

**Comment by darron** [comment]
Is this on current 1.4.1 octohost? Or 1.2?

**Comment by joshuacox** [comment]
probably old, though I'm not sure how to tell, perhaps an `octo version` would be a good option to implement.  I will rebuild, and reopen if it persists.

**Comment by darron** [comment]
If you have the `/etc/nginx/containers/` folder instead of the `/etc/nginx/containers.conf` file then you're on the newest.

If you're running docker 1.2 then it's 1.2 (unless you've upgraded docker manually).

If you haven't built it since January 23rd or so - it's 1.2.

Will add `octo version` to get some debugging information.

**Comment by joshuacox** [comment]
ok after, a rebuild, it seems consul doesn't like the private network here in KVM, and is dying:

```
==> Starting Consul agent...
==> Error starting agent: Failed to get advertise address: No private IP address found
==> WARNING: Bootstrap mode enabled! Do not enable unless necessary
==> WARNING: It is highly recommended to set GOMAXPROCS higher than 1
==> Starting Consul agent...
==> Error starting agent: Failed to get advertise address: No private IP address found
```
docker0 looks normal to me:
```
root@octo:~# ifconfig docker0
docker0   Link encap:Ethernet  HWaddr 56:84:7a:fe:97:99  
          inet addr:172.17.42.1  Bcast:0.0.0.0  Mask:255.255.0.0
          UP BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)
```

I'm not sure why consul is dying on that.

**Comment by darron** [comment]
Consul doesn't care about the docker0 ip address. There's something wrong with the Consul config file.

Take a look here:

https://gist.github.com/darron/fbcf00c2a3ee88de27cf

Instead of `PUBLIC_IPV4` - put whatever the IP address is of the box - if you follow that script with the new IP address it should reset the Consul config and data and startup.

**Comment by joshuacox** [comment]
Ok, consul is now running once I filled in the correct ip address in `/etc/consul.d/default.json` however, still getting weird errors when I upload even the default octohost harp or example:
```
remote: 2015/02/07 22:51:26 [ERR] (key "octohost/harp/DOMAINS") Unexpected response code: 500
remote: 2015/02/07 22:51:26 [ERR] (service "harp [passing]") Unexpected response code: 500 (No cluster leader)
```
and when I `octo status` it definitely acts as if it has indegistion at something I fed it:
```
# octo status
harp: parse error: Invalid numeric literal at line 1, column 4
DOWN
```
for sanity's sake, I'm building a fresh one in the background, but I thought I'd share these errors.  I'll report back once the other finishes and I duplicate the process.

**Comment by darron** [comment]
Those mean that Consul is confused and doesn't have consensus. 

If you didn't clear out the directory like in the gist then that usually happens. 

```service consul stop
rm -rf /the/directory/in/the/gist
service consul start
```

**Comment by joshuacox** [comment]
nice catch, indeed, I missed the rm -Rf step doing it by hand.  closing, thanks for the sanity check @darron !
